name: Automatizacao de Dados SFCR

on:
  schedule:
    - cron: '0 3 * * *' # Roda todos os dias às 03:00 da manhã
  workflow_dispatch: # Permite clique em um botão para rodar na hora que quiser

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dá permissão para o robô salvar o CSV no repositório
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests pandas

      - name: Executar script de coleta
        run: python coleta_dados.py

      - name: Salvar alterações (Commit e Push)
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add 1_irradiancia_NASA_SJBV_FromAPI.csv
          git commit -m "Atualização automática" || echo "Sem alterações para salvar"
          git push
